const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

function readProjectFile(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

function listProjectFiles(relativePath) {
  return fs.readdirSync(path.join(root, relativePath));
}

function readCssRule(source, selector) {
  const normalisedSource = source.replace(/\r\n/g, '\n');
  const normalisedSelector = selector.replace(/\r\n/g, '\n');
  const start = normalisedSource.indexOf(normalisedSelector);
  if (start < 0) return '';
  const open = normalisedSource.indexOf('{', start);
  const close = normalisedSource.indexOf('}', open);
  return normalisedSource.slice(open + 1, close);
}

describe('dashboard studio styles', () => {
  it('defines shared studio, motion, and dark-mode tokens', () => {
    const variables = readProjectFile('public/assets/scss/_variables.scss');
    const fontScss = readProjectFile('public/assets/scss/_fonts.scss');
    const fontLicense = readProjectFile('public/assets/fonts/HarmonyOS_Sans_LICENSE.txt');
    const fontFiles = listProjectFiles('public/assets/fonts');
    const css = readProjectFile('public/assets/css/site.css');
    const uiTokens = readProjectFile('ui/shared/design-system/tokens.ts');
    const customSelectScss = readProjectFile('public/assets/scss/components/_custom-select.scss');

    expect(fontScss).toContain("font-family: 'HarmonyOS Sans'");
    expect(fontScss).toContain("HarmonyOS_Sans_Regular.ttf");
    expect(fontScss).toContain("HarmonyOS_Sans_Bold_Italic.ttf");
    expect(fontScss).toContain('font-display: swap');
    expect(fontLicense).toContain('HarmonyOS Sans Fonts License Agreement');
    expect(fontFiles).toContain('HarmonyOS_Sans_Regular.ttf');
    expect(fontFiles).toContain('HarmonyOS_Sans_Medium.ttf');
    expect(fontFiles).toContain('HarmonyOS_Sans_Bold.ttf');
    expect(fontFiles).toContain('HarmonyOS_Sans_Regular_Italic.ttf');
    expect(variables).toContain('color-scheme: light dark');
    expect(variables).toContain("--font-body: 'HarmonyOS Sans', 'Noto Sans Variable', system-ui, sans-serif");
    expect(variables).toContain('--studio-canvas');
    expect(variables).toContain('--studio-shadow-control');
    expect(variables).toContain('--studio-shadow-control: 0 1px 2px rgba(15, 23, 42, 0.12)');
    expect(variables).toContain('0 4px 12px rgba(15, 23, 42, 0.10)');
    expect(variables).toContain('--studio-inline-create-width: 452px');
    expect(variables).toContain('--studio-inline-create-shadow: var(--studio-shadow-control)');
    expect(variables).toContain('--motion-duration-base');
    expect(variables).toContain('@media (prefers-color-scheme: dark)');
    expect(variables).toContain(':root[data-theme="dark"]');
    expect(variables).toContain('@media (prefers-reduced-motion: reduce)');
    expect(uiTokens).toContain('shadowControl');
    expect(uiTokens).toContain('0 4px 12px rgba(15, 23, 42, 0.10)');

    expect(css).toContain('color-scheme: light dark');
    expect(css).toContain('font-family: "HarmonyOS Sans"');
    expect(css).toContain('HarmonyOS_Sans_Regular.ttf');
    expect(css).toMatch(/--font-body: ['"]HarmonyOS Sans['"], ['"]Noto Sans Variable['"], system-ui, sans-serif/);
    expect(css).toContain('--studio-canvas');
    expect(css).toContain('--studio-shadow-control');
    expect(css).toContain('--studio-shadow-control: 0 1px 2px rgba(15, 23, 42, 0.12)');
    expect(css).toContain('--studio-inline-create-width: 452px');
    expect(css).toContain('--studio-inline-create-shadow: var(--studio-shadow-control)');
    expect(css).toContain('--motion-duration-base');
    expect(css).toContain('@media (prefers-color-scheme: dark)');
    expect(css).toContain(':root[data-theme=dark]');
    expect(customSelectScss).toContain('.custom-select__native');
    expect(customSelectScss).toContain('box-shadow: var(--studio-shadow-control)');
    expect(customSelectScss).toContain("mask: url('/assets/icons/chevron-down.svg')");
    expect(customSelectScss).toContain('@media (prefers-reduced-motion: reduce)');
    expect(css).toContain('.custom-select__native');
    expect(css).toContain('box-shadow: var(--studio-shadow-control)');
    expect(css).toContain('mask: url("/assets/icons/chevron-down.svg")');
  });

  it('keeps dashboard chrome on studio tokens instead of dotted surfaces', () => {
    const adminScss = readProjectFile('public/assets/scss/pages/_admin.scss');
    const siteCss = readProjectFile('public/assets/css/site.css');
    const adminHtml = readProjectFile('public/admin.html');
    const publicHtml = readProjectFile('public/index.html');
    const installHtml = readProjectFile('public/install.html');
    const loginHtml = readProjectFile('public/login.html');
    const registerHtml = readProjectFile('public/register.html');
    const mainHeaderPartial = readProjectFile('public/plainspace/partials/main-header.html');
    const topHeaderPartial = readProjectFile('public/plainspace/partials/top-header.html');
    const projectGlobeIcon = readProjectFile('public/assets/icons/globe-project.svg');
    const contentHeaderPartial = readProjectFile('public/plainspace/partials/content-header.html');
    const contentHeaderPagesPartial = readProjectFile('public/plainspace/partials/content-header-pages.html');
    const contentHeaderActionsTs = readProjectFile('ui/shell/dashboard/contentHeaderActions.ts');
    const topHeaderActionsTs = readProjectFile('ui/shell/dashboard/topHeaderActions.ts');
    const contentAreaScss = readProjectFile('public/assets/scss/components/_content-area.scss');
    const installScss = readProjectFile('public/assets/scss/pages/_install.scss');
    const gridModeScss = readProjectFile('public/assets/scss/components/_grid-mode.scss');
    const globalScss = readProjectFile('public/assets/scss/_global.scss');
    const externalLinksEntryTs = readProjectFile('ui/shared/entries/externalLinks.ts');
    const externalLinksWrapper = readProjectFile('public/assets/js/externalLinks.js');
    const runtimeWidgetShellTs = readProjectFile('ui/runtime/main/runtimeWidgetShell.ts');
    const adminGridCss = readCssRule(siteCss, '#adminGrid');
    const canvasGridContainCss = siteCss.match(/^\.canvas-grid\s*\{[^}]*\}/m)?.[0] ?? '';
    const mainHeaderCss = siteCss.match(/^\.main-header\s*\{[^}]*\}/m)?.[0] ?? '';
    const sidebarCss = readCssRule(siteCss, '.sidebar');
    const sidebarNavCss = readCssRule(siteCss, '.sidebar .sidebar-nav');
    const sidebarItemCss = readCssRule(siteCss, '.sidebar .sidebar-nav .sidebar-item, .sidebar .sidebar-nav .sidebar-add-subpage');
    const sidebarItemChromeCss = readCssRule(siteCss, '.sidebar .sidebar-nav .sidebar-item::before, .sidebar .sidebar-nav .sidebar-add-subpage::before');
    const sidebarHoverCss = readCssRule(siteCss, '.sidebar .sidebar-nav .sidebar-item:hover, .sidebar .sidebar-nav .sidebar-add-subpage:hover');
    const sidebarHoverChromeCss = readCssRule(siteCss, '.sidebar .sidebar-nav .sidebar-item:hover::before, .sidebar .sidebar-nav .sidebar-add-subpage:hover::before');
    const sidebarActiveCss = readCssRule(siteCss, '.sidebar .sidebar-nav .sidebar-item.active, .sidebar .sidebar-nav .active.sidebar-add-subpage');
    const contentHeaderCss = siteCss.match(/\.content-header\s*\{[^}]*\}/)?.[0] ?? '';
    const contentFooterPaddingCss = readCssRule(siteCss, 'body.has-content-footer #content');
    const devBannerFooterCss = readCssRule(siteCss, 'body.has-content-footer .dev-mode-banner');
    const canvasSelectedCss = siteCss.match(/body\.dashboard-edit-mode \.canvas-item\.selected\s*\{[^}]*\}/)?.[0] ?? '';
    const canvasDraggingCss = siteCss.match(/body\.dashboard-edit-mode \.canvas-item\.dragging,\s*body\.dashboard-edit-mode \.canvas-item\.is-dragging\s*\{[^}]*\}/)?.[0] ?? '';
    const canvasHoverCss = siteCss.match(/body\.dashboard-edit-mode \.canvas-item:not\(\.dragging\):not\(\.selected\):not\(\.is-dragging\):hover\s*\{[^}]*\}/)?.[0] ?? '';
    const boundingBoxCss = siteCss.match(/body\.grid-mode \.bounding-box\s*\{[^}]*\}/)?.[0] ?? '';
    const fieldFocusCss = readCssRule(siteCss, '.app-scope .field input:focus,\n.app-scope .field textarea:focus');
    const externalLinkCss = readCssRule(siteCss, '.app-scope a[data-external-link=true]');
    const externalLinkIconCss = readCssRule(siteCss, '.app-scope a[data-external-link=true]::after');
    const installPageCss = readCssRule(siteCss, '.app-scope.install-page');
    const installCardCss = readCssRule(siteCss, '.app-scope.install-page .login-form');
    const mainNavHoverCss = readCssRule(siteCss, '.main-header .nav-icons a:hover,\n.main-header .nav-icons .nav-button:hover');
    const mainNavHoverChromeCss = readCssRule(siteCss, '.main-header .nav-icons a:hover::before,\n.main-header .nav-icons .nav-button:hover::before');
    const mainNavActiveCss = readCssRule(siteCss, '.main-header .nav-icons a.active,\n.main-header .nav-icons .nav-button.active');
    const projectLinkCss = readCssRule(siteCss, '.top-header .left-icons a.project-link');
    const projectLinkChromeCss = readCssRule(siteCss, '.top-header .left-icons a.project-link::before');
    const projectLinkHoverCss = readCssRule(siteCss, '.top-header .left-icons a.project-link:hover,\n.top-header .left-icons a.project-link:focus-visible');
    const projectLinkHoverChromeCss = readCssRule(siteCss, '.top-header .left-icons a.project-link:hover::before,\n.top-header .left-icons a.project-link:focus-visible::before');
    const projectNameCss = readCssRule(siteCss, '.top-header .project-link__name');
    const projectIconCss = readCssRule(siteCss, '.top-header .left-icons a.project-link .icon');
    const searchContainerCss = readCssRule(siteCss, '.top-header .search-container');
    const searchContainerChromeCss = readCssRule(siteCss, '.top-header .search-container::before');
    const searchContainerHoverCss = readCssRule(siteCss, '.top-header .search-container:hover');
    const searchContainerHoverChromeCss = readCssRule(siteCss, '.top-header .search-container:hover::before');
    const searchContainerOpenCss = readCssRule(siteCss, '.top-header .search-container:focus-within, .top-header .search-container.open, .top-header .search-container.is-expanded');
    const searchToggleCss = readCssRule(siteCss, '.top-header .search-container #search-toggle');
    const searchInputOpenCss = readCssRule(siteCss, '.top-header .search-container.open input, .top-header .search-container.is-expanded input, .top-header .search-container:focus-within input');
    const inlineCreateCss = readCssRule(siteCss, '.inline-create-field');
    const inlineCreateOpenCss = readCssRule(siteCss, '.inline-create-field.open');
    const inlineCreateInputCss = readCssRule(siteCss, '.inline-create-field input');
    const inlineCreateIconButtonCss = readCssRule(siteCss, '.inline-create-field .icon-button');
    const inlineCreateShellCss = readCssRule(siteCss, '#subpage-floating-field,\n#workspace-floating-field');
    const widgetToggleCss = siteCss.match(/\.widgets-toggle\s*\{[^}]*position: fixed[^}]*\}/)?.[0] ?? '';
    const buttonScss = readProjectFile('public/assets/scss/components/_buttons.scss');
    const globalButtonCss = readCssRule(siteCss, '.app-scope .button');
    const globalButtonHoverCss = readCssRule(siteCss, '.app-scope .button:not(:disabled):hover');
    const dialogScss = readProjectFile('public/assets/scss/components/_dashboard-dialog.scss');
    const dashboardIconsScss = readProjectFile('public/assets/scss/components/_dashboard-icons.scss');
    const floatingLabelsScss = readProjectFile('public/assets/scss/components/_floating-labels.scss');
    const workspacesJs = readProjectFile('ui/shell/dashboard/workspaces.js');
    const searchExpansionTs = readProjectFile('ui/shell/search/searchExpansion.ts');
    const siteScss = readProjectFile('public/assets/scss/site.scss');

    expect(adminScss).toContain('background: var(--studio-canvas)');
    expect(adminScss).toContain('display: grid');
    expect(adminScss).toContain('grid-auto-flow: row dense');
    expect(adminScss).toContain('gap: var(--dashboard-grid-gap)');
    expect(adminScss).toContain("[data-dashboard-column]");
    expect(adminScss).toContain('--dashboard-min-height');
    expect(adminScss).toContain('.dashboard-drop-placeholder');
    expect(adminScss).toContain('.dashboard-drag-preview');
    expect(adminScss).toContain('is-dashboard-snap-active');
    expect(adminScss).toContain('@keyframes dashboard-snap-pulse');
    expect(adminScss).toContain('--dashboard-placeholder-height');
    expect(adminScss).toContain("[data-dashboard-height-mode='scroll'] .canvas-item-content");
    expect(adminScss).toContain('padding: 0 0 clamp(56px, 6vw, 96px)');
    expect(adminScss).not.toContain('radial-gradient');
    expect(adminGridCss).toContain('background: var(--studio-canvas)');
    expect(adminGridCss).toContain('display: grid');
    expect(adminGridCss).toContain('grid-auto-flow: row dense');
    expect(adminGridCss).toContain('gap: var(--dashboard-grid-gap)');
    expect(siteCss).toContain('[data-dashboard-column]');
    expect(siteCss).toContain('--dashboard-min-height');
    expect(siteCss).toContain('.dashboard-drop-placeholder');
    expect(siteCss).toContain('.dashboard-drag-preview');
    expect(siteCss).toContain('is-dashboard-snap-active');
    expect(siteCss).toContain('@keyframes dashboard-snap-pulse');
    expect(siteCss).toContain('--dashboard-placeholder-height');
    expect(siteCss).toContain('[data-dashboard-height-mode=scroll] .canvas-item-content');
    expect(adminGridCss).toContain('padding: 0 0 clamp(56px, 6vw, 96px)');
    expect(adminGridCss).not.toContain('padding: clamp(28px');
    expect(adminGridCss).not.toContain('radial-gradient');
    expect(contentAreaScss).toContain('contain: layout size');
    expect(contentAreaScss).toContain('#adminGrid.canvas-grid');
    expect(contentAreaScss).toContain('contain: none');
    expect(contentAreaScss).toContain('min-height: var(--dashboard-min-height, 0)');
    expect(contentAreaScss).not.toContain('contain: layout paint size');
    expect(canvasGridContainCss).toContain('contain: layout size');
    expect(canvasGridContainCss).not.toContain('paint');
    expect(widgetToggleCss).toContain('var(--studio-surface-solid)');
    expect(widgetToggleCss).toContain('var(--studio-radius-control)');
    expect(sidebarCss).toContain('position: relative');
    expect(sidebarCss).toContain('overflow: visible');
    expect(sidebarNavCss).toContain('z-index: 1');
    expect(sidebarNavCss).toContain('overflow: visible');
    expect(sidebarItemCss).toContain('background: var(--studio-surface-solid)');
    expect(sidebarItemCss).toContain('border: 0');
    expect(sidebarItemCss).toContain('box-shadow: none');
    expect(sidebarItemCss).toContain('z-index: 1');
    expect(sidebarItemCss).toContain('isolation: isolate');
    expect(sidebarItemChromeCss).toContain('background: var(--studio-surface-solid)');
    expect(sidebarItemChromeCss).toContain('box-shadow: var(--studio-shadow-control)');
    expect(sidebarItemChromeCss).toContain('transform-origin: center');
    expect(sidebarItemChromeCss).toContain('transform var(--motion-duration-base)');
    expect(sidebarHoverCss).toContain('background: transparent');
    expect(sidebarHoverCss).toContain('transform: none');
    expect(sidebarHoverCss).not.toContain('transform: scale(1.045)');
    expect(sidebarHoverChromeCss).toContain('background: var(--studio-surface-solid)');
    expect(sidebarHoverChromeCss).toContain('box-shadow: var(--studio-shadow-control)');
    expect(sidebarHoverChromeCss).toContain('transform: scale(1.045)');
    expect(sidebarHoverCss).not.toContain('translateY(-1px)');
    expect(sidebarHoverCss).not.toContain('var(--user-color)');
    expect(sidebarActiveCss).toContain('box-shadow: none');
    expect(sidebarActiveCss).not.toContain('var(--studio-focus-ring)');
    expect(mainHeaderPartial).toContain('id="workspace-actions"');
    expect(mainHeaderPartial).toContain('nav-icons--end');
    expect(siteCss).toContain('.main-header .nav-icons--end');
    expect(siteCss).toContain('margin-left: auto');
    expect(mainHeaderCss).toContain('background: transparent');
    expect(mainHeaderCss).toContain('border-bottom: 0');
    expect(mainHeaderCss).toContain('backdrop-filter: none');
    expect(siteCss).toContain('.main-header .nav-icons a .label');
    expect(siteCss).toContain('font-size: 0.86rem');
    expect(siteCss).toContain('.main-header .nav-icons--end a .label');
    expect(siteCss).toContain('clip-path: none');
    expect(siteCss).toContain('clip-path: inset(50%)');
    expect(inlineCreateCss).toContain('gap: var(--studio-inline-create-gap)');
    expect(inlineCreateOpenCss).toContain('width: min(var(--studio-inline-create-width), calc(100vw - 128px))');
    expect(inlineCreateInputCss).toContain('height: var(--studio-control-size)');
    expect(inlineCreateInputCss).toContain('background-color: var(--studio-inline-create-input-surface)');
    expect(inlineCreateInputCss).toContain('box-shadow: var(--studio-inline-create-shadow)');
    expect(inlineCreateIconButtonCss).toContain('width: var(--studio-control-size)');
    expect(inlineCreateIconButtonCss).toContain('box-shadow: var(--studio-inline-create-shadow)');
    expect(inlineCreateShellCss).toContain('background: transparent');
    expect(inlineCreateShellCss).toContain('padding: var(--studio-inline-create-padding)');
    expect(inlineCreateShellCss).toContain('box-shadow: var(--studio-inline-create-panel-shadow)');
    expect(workspacesJs).toContain("DETACHED_WORKSPACE_ACTION_SLUGS = new Set(['settings'])");
    expect(workspacesJs).toContain('function buildWorkspaceActions');
    expect(workspacesJs).toContain("label.className = 'label'");
    expect(workspacesJs).toContain("anchor.setAttribute('aria-label', title)");
    expect(workspacesJs).not.toContain('anchor.title = title');
    expect(workspacesJs).not.toContain("button.title = 'Create workspace'");
    expect(floatingLabelsScss).toContain(':where(.top-header, .main-header, .content-header, .sidebar)');
    expect(siteCss).toContain(':where(.top-header, .main-header, .content-header, .sidebar) [aria-label]::after');
    expect(siteCss).toContain('content: none');
    expect(fieldFocusCss).toContain('border-color: transparent');
    expect(fieldFocusCss).toContain('box-shadow: var(--studio-focus-ring)');
    expect(globalScss).toContain('a[data-external-link="true"]');
    expect(globalScss).toContain('content: "\\2197"');
    expect(externalLinkCss).toContain('text-decoration: none');
    expect(externalLinkIconCss).toContain('content: "\\2197"');
    expect(externalLinkIconCss).toContain('opacity: 0.7');
    expect(externalLinksEntryTs).toContain("import '../controls/externalLinks.js'");
    expect(externalLinksWrapper).toContain("../../../ui/shared/controls/externalLinks.js");
    [adminHtml, publicHtml, installHtml, loginHtml, registerHtml].forEach(html => {
      expect(html).toContain('/build/externalLinks.js');
    });
    expect(installScss).toContain('background: var(--studio-canvas)');
    expect(installScss).toContain('background: var(--studio-surface-solid)');
    expect(installScss).not.toContain('radial-gradient');
    expect(installScss).not.toContain('.app-scope.install-page .button.primary');
    expect(installPageCss).toContain('background: var(--studio-canvas)');
    expect(installPageCss).toContain('color: var(--studio-text)');
    expect(installCardCss).toContain('background: var(--studio-surface-solid)');
    expect(installCardCss).toContain('border: 1px solid var(--studio-border)');
    expect(installCardCss).toContain('box-shadow: var(--studio-shadow-soft)');
    expect(siteCss).not.toContain('.app-scope.install-page .button.primary');
    expect(mainNavHoverCss).toContain('background: transparent');
    expect(mainNavHoverCss).toContain('transform: none');
    expect(mainNavHoverCss).not.toContain('transform: scale(1.035)');
    expect(mainNavHoverChromeCss).toContain('background: var(--studio-surface-solid)');
    expect(mainNavHoverChromeCss).toContain('transform: scale(1.035)');
    expect(mainNavHoverCss).not.toContain('var(--user-color)');
    expect(mainNavActiveCss).toContain('background: transparent');
    expect(mainNavActiveCss).toContain('border-color: transparent');
    expect(mainNavActiveCss).toContain('box-shadow: none');
    expect(mainNavActiveCss).not.toContain('var(--studio-focus-ring)');
    expect(mainNavActiveCss).not.toContain('var(--user-color)');
    expect(buttonScss).toContain('--btn-radius: var(--studio-radius-control)');
    expect(buttonScss).toContain('border:0');
    expect(buttonScss).toContain('--btn-hover-delay: 80ms');
    expect(buttonScss).toContain('box-shadow var(--motion-duration-slow) var(--motion-ease-standard) var(--btn-hover-delay)');
    expect(buttonScss).toContain('box-shadow: var(--btn-hover-shadow)');
    expect(buttonScss).not.toContain('transform: scale');
    expect(buttonScss).not.toContain('border:1px solid var(--bd)');
    expect(buttonScss).not.toContain('border-color var(--motion-duration-fast)');
    expect(buttonScss).not.toContain('--bd:');
    expect(globalButtonCss).toContain('border: 0');
    expect(globalButtonCss).toContain('box-shadow var(--motion-duration-slow) var(--motion-ease-standard) var(--btn-hover-delay)');
    expect(globalButtonCss).not.toContain('transform-origin');
    expect(globalButtonCss).not.toContain('border-color');
    expect(globalButtonHoverCss).toContain('box-shadow: var(--btn-hover-shadow)');
    expect(globalButtonHoverCss).not.toContain('transform: scale');
    expect(siteCss).toContain('#content.is-content-refreshing');
    expect(topHeaderPartial).toContain('class="project-link"');
    expect(topHeaderPartial).toContain('id="project-name"');
    expect(topHeaderPartial).toContain('/assets/icons/globe-project.svg');
    expect(projectGlobeIcon).toContain('stroke-width="1.6"');
    expect(topHeaderPartial).toContain('Blogposter');
    expect(topHeaderPartial).not.toContain('title="Open public site');
    expect(contentHeaderPartial).not.toContain(' title=');
    expect(contentHeaderPagesPartial).not.toContain(' title=');
    expect(contentHeaderCss).toContain('position: fixed');
    expect(contentHeaderCss).toContain('bottom: 0');
    expect(contentHeaderCss).toContain('left: 88px');
    expect(contentHeaderCss).toContain('z-index: 70');
    expect(contentFooterPaddingCss).toContain('padding-bottom: calc(var(--studio-content-footer-height, 60px) + 16px)');
    expect(devBannerFooterCss).toContain('bottom: calc(var(--studio-content-footer-height, 60px) + 8px)');
    expect(contentAreaScss).toContain('outline-color: var(--studio-border-strong)');
    expect(contentAreaScss).not.toContain('outline-color: var(--user-color)');
    expect(gridModeScss).toContain('border: 1px dashed var(--studio-border-strong)');
    expect(gridModeScss).not.toContain('border: 1px dashed var(--user-color');
    expect(globalScss).toContain('box-shadow: var(--studio-shadow-soft)');
    expect(runtimeWidgetShellTs).toContain('background:var(--studio-border-strong');
    expect(runtimeWidgetShellTs).not.toContain('background:var(--user-color');
    expect(canvasSelectedCss).toContain('outline-color: var(--studio-border-strong)');
    expect(canvasSelectedCss).toContain('box-shadow: var(--studio-shadow-soft)');
    expect(canvasSelectedCss).not.toContain('var(--user-color)');
    expect(canvasDraggingCss).toContain('outline-color: var(--studio-border-strong)');
    expect(canvasDraggingCss).toContain('box-shadow: var(--studio-shadow-lift)');
    expect(canvasDraggingCss).not.toContain('var(--user-color)');
    expect(canvasHoverCss).toContain('border-color: var(--studio-border-strong)');
    expect(canvasHoverCss).toContain('outline-color: var(--studio-border-strong)');
    expect(canvasHoverCss).not.toContain('var(--user-color)');
    expect(boundingBoxCss).toContain('border: 1px dashed var(--studio-border-strong)');
    expect(boundingBoxCss).not.toContain('var(--user-color)');
    expect(contentHeaderActionsTs).toContain("classList.toggle('has-content-footer', Boolean(header))");
    expect(topHeaderActionsTs).toContain("homeLink.removeAttribute('title')");
    expect(topHeaderActionsTs).toContain('setSearchExpanded(searchContainer, searchInput, expanded)');
    expect(searchExpansionTs).toContain("searchContainer.classList.toggle('is-expanded', expanded)");
    expect(searchExpansionTs).toContain("tokenValue(SEARCH_OPEN_WIDTH_TOKEN, SEARCH_OPEN_WIDTH_FALLBACK)");
    expect(siteCss).toContain('.top-header .left-icons a.project-link');
    expect(siteCss).toContain('max-width: min(220px, 44vw)');
    expect(projectLinkCss).toContain('border-color: transparent');
    expect(projectLinkCss).toContain('box-shadow: none');
    expect(projectLinkCss).toContain('isolation: isolate');
    expect(projectLinkChromeCss).toContain('transform: scale(1)');
    expect(projectLinkHoverCss).toContain('border-color: transparent');
    expect(projectLinkHoverCss).toContain('transform: none');
    expect(projectLinkHoverChromeCss).toContain('border-color: color-mix(in srgb, var(--user-color) 20%, var(--studio-border))');
    expect(projectLinkHoverChromeCss).toContain('transform: scale(1.015)');
    expect(siteCss).toContain('.top-header .project-link__name');
    expect(siteCss).toContain('text-overflow: ellipsis');
    expect(projectNameCss).toContain('font-weight: 400');
    expect(projectIconCss).toContain('width: 17px');
    expect(projectIconCss).toContain('height: 17px');
    expect(searchContainerCss).toContain('border: 1px solid transparent');
    expect(searchContainerCss).toContain('box-shadow: none');
    expect(searchContainerCss).toContain('isolation: isolate');
    expect(searchContainerChromeCss).toContain('transform-origin: left center');
    expect(searchContainerHoverCss).toContain('border-color: transparent');
    expect(searchContainerHoverCss).toContain('transform: none');
    expect(searchContainerHoverChromeCss).toContain('border-color: color-mix(in srgb, var(--user-color) 20%, var(--studio-border))');
    expect(searchContainerHoverChromeCss).toContain('transform: scale(1.015)');
    expect(searchContainerOpenCss).toContain('width: var(--studio-header-search-open-width)');
    expect(searchContainerOpenCss).toContain('max-width: calc(100vw - 128px)');
    expect(searchContainerOpenCss).toContain('border-color: transparent');
    expect(searchToggleCss).toContain('border: 0');
    expect(searchInputOpenCss).toContain('width: 100%');
    expect(searchInputOpenCss).toContain('padding-right: 12px');
    expect(topHeaderPartial).toContain('id="theme-mode-toggle"');
    expect(topHeaderPartial).toContain('id="account-menu-toggle"');
    expect(topHeaderPartial).toContain('id="account-menu-dropdown"');
    expect(topHeaderPartial).toContain('role="menu"');
    expect(topHeaderPartial).toContain('class="account-menu__item"');
    expect(topHeaderPartial).toContain('class="top-header__icon-button"');
    expect(siteCss).toContain('.top-header .account-menu__dropdown');
    expect(siteCss).toContain('.top-header .account-menu__item');
    expect(siteScss).toContain("@use 'components/dashboard-dialog'");
    expect(siteScss).toContain("@use 'components/dashboard-icons'");
    expect(dashboardIconsScss).toContain('@mixin dark-dashboard-icons');
    expect(dashboardIconsScss).toContain('.top-header .account-menu__item .icon');
    expect(dashboardIconsScss).toContain('filter: brightness(0) invert(1)');
    expect(dashboardIconsScss).toContain('opacity: 1');
    expect(siteCss).toContain(':root[data-theme=dark] .sidebar .sidebar-nav .sidebar-item .icon');
    expect(siteCss).toContain(':root[data-theme=dark] .top-header .top-header__icon-button .icon');
    expect(siteCss).toContain('filter: brightness(0) invert(1)');
    expect(dialogScss).toContain('background: var(--studio-surface)');
    expect(dialogScss).toContain('.bp-dialog__actions .button');
    expect(dialogScss).toContain('@media (prefers-reduced-motion: reduce)');
    expect(siteCss).toContain('.bp-dialog-root');
    expect(siteCss).toContain('var(--studio-shadow-lift)');
  });

  it('keeps the Designer app on the dashboard Studio theme contract', () => {
    const designerVariables = readProjectFile('apps/designer/assets/scss/_variables.scss');
    const designerScss = readProjectFile('apps/designer/assets/scss/designer.scss');
    const sceneBuilderScss = readProjectFile('apps/designer/assets/scss/_scene-builder.scss');
    const designerCss = readProjectFile('apps/designer/assets/css/designer.css');
    const designerApp = readProjectFile('ui/designer/app/index.ts');
    const themeModeSource = readProjectFile('ui/shell/theme/userColor.ts');

    expect(designerScss).toContain("@use '../../../../public/assets/scss/variables' as *");
    expect(designerScss).toContain('background: var(--designer-canvas)');
    expect(designerVariables).toContain('--designer-surface: var(--studio-surface-solid)');
    expect(designerVariables).toContain('--designer-shadow-lift: var(--studio-shadow-lift)');
    expect(designerVariables).toContain(':root:not([data-theme="light"])');
    expect(designerVariables).toContain(':root[data-theme="light"]');
    expect(designerVariables).toContain(':root[data-theme="dark"]');
    expect(sceneBuilderScss).toContain('--scene-ink: var(--designer-text)');
    expect(sceneBuilderScss).toContain('background: var(--scene-surface-glass)');
    expect(sceneBuilderScss).toContain('background: var(--scene-surface)');
    expect(designerApp).toContain('applyThemeMode();');
    expect(themeModeSource).toContain('bindThemeModeStorageSync');
    expect(themeModeSource).toContain("event.key !== THEME_MODE_STORAGE_KEY");

    expect(designerCss).toContain('--designer-surface: var(--studio-surface-solid)');
    expect(designerCss).toContain(':root:not([data-theme=light])');
    expect(designerCss).toContain(':root[data-theme=dark]');
    expect(designerCss).toContain('background: var(--designer-canvas)');
    expect(designerCss).toContain('background: var(--scene-surface-glass)');
    expect(designerCss).toContain('box-shadow: var(--designer-shadow-lift)');
  });
});
