'use strict';

const { BACKEND_EVENTS } = require('../contracts/generatedBackendEventCatalog');

const {
  HTTP_DIRECT_EVENT_CONTRACTS,
  HTTP_PUBLIC_EVENT_CONTRACTS,
  HTTP_PUBLIC_TOKEN_EVENT_CONTRACTS
} = require('../contracts/backendEventContracts');

// The transport allowlists are derived from the executable contracts so a new
// public event cannot silently drift away from its schema and timeout policy.
const HTTP_PUBLIC_EVENTS = new Set(HTTP_PUBLIC_EVENT_CONTRACTS.map(contract => contract.eventName));
const HTTP_PUBLIC_TOKEN_EVENTS = new Set(
  HTTP_PUBLIC_TOKEN_EVENT_CONTRACTS.map(contract => contract.eventName)
);
const HTTP_DIRECT_CONTRACT_EVENTS = new Set(
  HTTP_DIRECT_EVENT_CONTRACTS.map(contract => contract.eventName)
);

const AGENT_ACCESS_EVENTS = new Set([
  BACKEND_EVENTS.AGENT_ACCESS_CREATE_CODE,
  BACKEND_EVENTS.AGENT_ACCESS_CREATE_DEV_SESSION,
  BACKEND_EVENTS.AGENT_ACCESS_EXCHANGE_CODE,
  BACKEND_EVENTS.AGENT_ACCESS_LIST_CODES,
  BACKEND_EVENTS.AGENT_ACCESS_REVOKE_CODE
]);

const AGENT_SURFACE_BRIDGE_EVENTS = new Set([
  BACKEND_EVENTS.AGENT_GET_CAPABILITIES,
  BACKEND_EVENTS.AGENT_GET_API_DEFINITION,
  BACKEND_EVENTS.AGENT_GET_SURFACE_CONTEXT,
  BACKEND_EVENTS.AGENT_GET_SURFACE_ACTION,
  BACKEND_EVENTS.AGENT_LIST_SURFACE_ACTIONS,
  BACKEND_EVENTS.AGENT_LIST_SURFACE_COMMANDS,
  BACKEND_EVENTS.AGENT_PUBLISH_SURFACE_SNAPSHOT,
  BACKEND_EVENTS.AGENT_POLL_SURFACE_COMMANDS,
  BACKEND_EVENTS.AGENT_ACK_SURFACE_COMMAND
]);

const AGENT_MANAGER_EVENTS = new Set([
  ...AGENT_SURFACE_BRIDGE_EVENTS,
  BACKEND_EVENTS.AGENT_GET_SYSTEM_CONTEXT,
  BACKEND_EVENTS.AGENT_LIST_SURFACE_SNAPSHOTS,
  BACKEND_EVENTS.AGENT_GET_SURFACE_SNAPSHOT,
  BACKEND_EVENTS.AGENT_GET_SURFACE_PREVIEW,
  BACKEND_EVENTS.AGENT_INSPECT_SURFACE,
  BACKEND_EVENTS.AGENT_VALIDATE_SURFACE_COMMAND,
  BACKEND_EVENTS.AGENT_VALIDATE_SURFACE_WORKFLOW,
  BACKEND_EVENTS.AGENT_LIST_ACTIVITY,
  BACKEND_EVENTS.AGENT_ENQUEUE_SURFACE_COMMAND,
  BACKEND_EVENTS.AGENT_INVOKE_SURFACE_COMMAND,
  BACKEND_EVENTS.AGENT_INVOKE_SURFACE_COMMAND_AND_OBSERVE,
  BACKEND_EVENTS.AGENT_REFRESH_SURFACE,
  BACKEND_EVENTS.AGENT_INVOKE_SURFACE_WORKFLOW,
  BACKEND_EVENTS.AGENT_GET_SURFACE_COMMAND,
  BACKEND_EVENTS.AGENT_WAIT_FOR_SURFACE_COMMAND
]);

const PLAINSPACE_PRESENTATION_EVENTS = new Set([
  BACKEND_EVENTS.DELETE_LAYOUT_TEMPLATE,
  BACKEND_EVENTS.GET_ALL_LAYOUTS_FOR_PAGE,
  BACKEND_EVENTS.GET_ENVELOPE,
  BACKEND_EVENTS.GET_GLOBAL_LAYOUT_TEMPLATE,
  BACKEND_EVENTS.GET_LAYOUT_FOR_VIEWPORT,
  BACKEND_EVENTS.GET_LAYOUT_TEMPLATE,
  BACKEND_EVENTS.GET_LAYOUT_TEMPLATE_NAMES,
  BACKEND_EVENTS.GET_PUBLISHED_DESIGN_META,
  BACKEND_EVENTS.GET_WIDGET_INSTANCE,
  BACKEND_EVENTS.SAVE_LAYOUT_FOR_VIEWPORT,
  BACKEND_EVENTS.SAVE_LAYOUT_TEMPLATE,
  BACKEND_EVENTS.SAVE_PUBLISHED_DESIGN_META,
  BACKEND_EVENTS.SAVE_WIDGET_INSTANCE,
  BACKEND_EVENTS.SET_GLOBAL_LAYOUT_TEMPLATE,
  BACKEND_EVENTS.WIDGET_REGISTRY_REQUEST_V1
]);

const DESIGNER_MANAGER_EVENTS = new Set([
  BACKEND_EVENTS.DESIGNER_GET_DESIGN,
  BACKEND_EVENTS.DESIGNER_GET_LAYOUT,
  BACKEND_EVENTS.DESIGNER_LIST_DESIGNS,
  BACKEND_EVENTS.DESIGNER_LIST_LAYOUTS,
  BACKEND_EVENTS.DESIGNER_SAVE_DESIGN
]);

const HTTP_FORBIDDEN_EXTERNAL_EVENTS = new Set([
  BACKEND_EVENTS.ACQUIRE_CONTENT_LOCK,
  BACKEND_EVENTS.ADD_NAVIGATION_MENU_ITEM,
  BACKEND_EVENTS.ACTIVATE_MODULE_IN_REGISTRY,
  BACKEND_EVENTS.APPLY_SCHEMA_DEFINITION,
  BACKEND_EVENTS.APPLY_SCHEMA_FILE,
  BACKEND_EVENTS.APPROVE_CONTENT_REVIEW,
  BACKEND_EVENTS.CREATE_DATABASE,
  BACKEND_EVENTS.CREATE_CONTENT_ENTRY,
  BACKEND_EVENTS.CREATE_CONTENT_PREVIEW_TOKEN,
  BACKEND_EVENTS.COLOR_LIBRARY_CREATE,
  BACKEND_EVENTS.COLOR_LIBRARY_CREATE_SCHEME,
  BACKEND_EVENTS.COLOR_LIBRARY_DELETE,
  BACKEND_EVENTS.COLOR_LIBRARY_DELETE_SCHEME,
  BACKEND_EVENTS.COLOR_LIBRARY_ACTIVATE_SCHEME,
  BACKEND_EVENTS.COLOR_LIBRARY_LIST,
  BACKEND_EVENTS.COLOR_LIBRARY_LIST_PUBLIC,
  BACKEND_EVENTS.COLOR_LIBRARY_UPDATE,
  BACKEND_EVENTS.COLOR_LIBRARY_UPDATE_SCHEME,
  BACKEND_EVENTS.FONT_PACKAGES_ACTIVATE,
  BACKEND_EVENTS.FONT_PACKAGES_CREATE,
  BACKEND_EVENTS.FONT_PACKAGES_DELETE,
  BACKEND_EVENTS.FONT_PACKAGES_GET_PUBLIC,
  BACKEND_EVENTS.FONT_PACKAGES_LIST,
  BACKEND_EVENTS.FONT_PACKAGES_RESET_ROLE,
  BACKEND_EVENTS.SITE_PRESETS_APPLY,
  BACKEND_EVENTS.SITE_PRESETS_CREATE,
  BACKEND_EVENTS.SITE_PRESETS_DELETE,
  BACKEND_EVENTS.SITE_PRESETS_LIST,
  BACKEND_EVENTS.FONT_PACKAGES_UPDATE,
  BACKEND_EVENTS.FONT_PACKAGES_UPDATE_ROLE,
  BACKEND_EVENTS.CREATE_MEDIA_ATTACHMENT,
  BACKEND_EVENTS.CREATE_TRANSLATED_TEXT,
  BACKEND_EVENTS.CREATE_WIDGET,
  BACKEND_EVENTS.DB_DELETE,
  BACKEND_EVENTS.DB_INSERT,
  BACKEND_EVENTS.DB_SELECT,
  BACKEND_EVENTS.DB_UPDATE,
  BACKEND_EVENTS.DELETE_CONTENT_AUTOSAVE,
  BACKEND_EVENTS.DELETE_MEDIA_ATTACHMENT,
  BACKEND_EVENTS.DELETE_MEDIA_VARIANT,
  BACKEND_EVENTS.DELETE_MODULE_SETTING,
  BACKEND_EVENTS.DELETE_NAVIGATION_MENU_ITEM,
  BACKEND_EVENTS.DELETE_SEO_META,
  BACKEND_EVENTS.DELETE_SETTING,
  BACKEND_EVENTS.DELETE_TRANSLATED_TEXT,
  BACKEND_EVENTS.DELETE_TRANSLATION_LANGUAGE,
  BACKEND_EVENTS.DELETE_WIDGET,
  BACKEND_EVENTS.DEACTIVATE_MODULE,
  BACKEND_EVENTS.DEACTIVATE_MODULE_IN_REGISTRY,
  BACKEND_EVENTS.CHECK_MODULE_UPDATES,
  BACKEND_EVENTS.INSTALL_APP_FROM_DIRECTORY,
  BACKEND_EVENTS.INSPECT_MODULE_UPDATE,
  BACKEND_EVENTS.INSPECT_MODULE_ZIP_ACCESS,
  BACKEND_EVENTS.INSTALL_MODULE_UPDATE,
  BACKEND_EVENTS.INSTALL_MODULE_FROM_ZIP,
  BACKEND_EVENTS.ISSUE_MODULE_TOKEN,
  BACKEND_EVENTS.ISSUE_USER_TOKEN,
  BACKEND_EVENTS.LIST_PENDING_MODULE_ACCESS_REQUESTS,
  'localDbDelete',
  'localDbInsert',
  'localDbSelect',
  'localDbUpdate',
  BACKEND_EVENTS.LINK_MEDIA_TO_CONTENT,
  BACKEND_EVENTS.PERFORM_DB_OPERATION,
  BACKEND_EVENTS.PUBLISH_CONTENT_ENTRY,
  BACKEND_EVENTS.REGISTER_LOGIN_STRATEGY,
  BACKEND_EVENTS.REGISTER_WIDGET_USAGE,
  BACKEND_EVENTS.REGISTER_CONTENT_TYPE,
  BACKEND_EVENTS.REGISTER_MODULE_SETTINGS_SCHEMA,
  BACKEND_EVENTS.REGISTER_SETTINGS_SECTION,
  BACKEND_EVENTS.REFRESH_CONTENT_LOCK,
  BACKEND_EVENTS.REFRESH_ACCESS_TOKEN,
  BACKEND_EVENTS.REJECT_CONTENT_REVIEW,
  BACKEND_EVENTS.RELEASE_CONTENT_LOCK,
  BACKEND_EVENTS.RESTORE_CONTENT_ENTRY,
  BACKEND_EVENTS.RESTORE_CONTENT_REVISION,
  BACKEND_EVENTS.RESOLVE_MODULE_ACCESS_REQUEST,
  BACKEND_EVENTS.SET_MODULE_UPDATE_SOURCE,
  BACKEND_EVENTS.REVOKE_ALL_TOKENS_FOR_USER,
  BACKEND_EVENTS.REVOKE_REFRESH_TOKEN,
  BACKEND_EVENTS.REVOKE_TOKEN,
  BACKEND_EVENTS.RUN_EXPORT,
  BACKEND_EVENTS.RUN_IMPORT,
  BACKEND_EVENTS.RESCAN_APPS,
  BACKEND_EVENTS.SAVE_CONTENT_AUTOSAVE,
  BACKEND_EVENTS.SAVE_LAYOUT_V1,
  BACKEND_EVENTS.SET_NAVIGATION_MENU_ITEMS,
  BACKEND_EVENTS.SET_SEO_DEFAULTS,
  BACKEND_EVENTS.SET_SETTINGS,
  BACKEND_EVENTS.SET_SETTING,
  BACKEND_EVENTS.SET_MODULE_TOKEN_EXPIRY,
  BACKEND_EVENTS.SET_USER_TOKEN_EXPIRY,
  BACKEND_EVENTS.SUBMIT_CONTENT_REVIEW,
  BACKEND_EVENTS.TRASH_CONTENT_ENTRY,
  BACKEND_EVENTS.UNLINK_MEDIA_FROM_CONTENT,
  BACKEND_EVENTS.UNINSTALL_APP,
  BACKEND_EVENTS.UPDATE_CONTENT_ENTRY,
  BACKEND_EVENTS.UPDATE_MEDIA_ATTACHMENT,
  BACKEND_EVENTS.UPDATE_MODULE_SETTING_VALUE,
  BACKEND_EVENTS.UPDATE_MODULE_SETTINGS,
  BACKEND_EVENTS.UPDATE_NAVIGATION_MENU_ITEM,
  BACKEND_EVENTS.UPDATE_TRANSLATED_TEXT,
  BACKEND_EVENTS.UPSERT_MEDIA_VARIANT,
  BACKEND_EVENTS.UPSERT_NAVIGATION_MENU,
  BACKEND_EVENTS.UPSERT_SEO_META,
  BACKEND_EVENTS.UPSERT_TRANSLATED_TEXT,
  BACKEND_EVENTS.UPSERT_TRANSLATION_LANGUAGE,
  BACKEND_EVENTS.UPDATE_WIDGET,
  BACKEND_EVENTS.CREATE_PAGE,
  BACKEND_EVENTS.UPDATE_PAGE,
  BACKEND_EVENTS.SET_AS_DELETED,
  BACKEND_EVENTS.SET_AS_START,
  BACKEND_EVENTS.DELETE_PAGE,
  BACKEND_EVENTS.CREATE_USER,
  BACKEND_EVENTS.UPDATE_USER_PROFILE,
  BACKEND_EVENTS.DELETE_USER,
  BACKEND_EVENTS.SET_USER_ACCESS,
  BACKEND_EVENTS.GET_ALL_USERS,
  BACKEND_EVENTS.GET_USER_ACCESS,
  BACKEND_EVENTS.GET_USER_DETAILS_BY_ID,
  BACKEND_EVENTS.GET_USER_DETAILS_BY_USERNAME,
  BACKEND_EVENTS.GET_CONTENT_AUTOSAVE,
  BACKEND_EVENTS.GET_CONTENT_ENTRY,
  BACKEND_EVENTS.GET_CONTENT_ENTRY_BY_SOURCE,
  BACKEND_EVENTS.GET_CONTENT_LOCK,
  BACKEND_EVENTS.GET_CONTENT_REVIEW,
  BACKEND_EVENTS.GET_CONTENT_REVISION,
  BACKEND_EVENTS.GET_CONTENT_REVISIONS,
  BACKEND_EVENTS.GET_CONTENT_TYPE,
  BACKEND_EVENTS.GET_MEDIA_ATTACHMENT,
  BACKEND_EVENTS.GET_MODULE_SETTINGS,
  BACKEND_EVENTS.GET_MODULE_SETTINGS_SCHEMA,
  BACKEND_EVENTS.GET_MODULE_SETTING_VALUE,
  BACKEND_EVENTS.GET_NAVIGATION_MENU,
  BACKEND_EVENTS.GET_NAVIGATION_TREE,
  BACKEND_EVENTS.GET_SEO_DEFAULTS,
  BACKEND_EVENTS.GET_SEO_META,
  BACKEND_EVENTS.GET_TRANSLATED_TEXT,
  BACKEND_EVENTS.GET_TRANSLATION_LANGUAGE,
  BACKEND_EVENTS.GET_WIDGETS,
  BACKEND_EVENTS.LIST_CONTENT_AUTOSAVES,
  BACKEND_EVENTS.LIST_CONTENT_ENTRIES,
  BACKEND_EVENTS.LIST_CONTENT_FOR_MEDIA,
  BACKEND_EVENTS.LIST_CONTENT_REVIEW_QUEUE,
  BACKEND_EVENTS.LIST_CONTENT_TYPES,
  BACKEND_EVENTS.LIST_LANGUAGES,
  BACKEND_EVENTS.LIST_MEDIA_ATTACHMENTS,
  BACKEND_EVENTS.LIST_MEDIA_FOR_CONTENT,
  BACKEND_EVENTS.LIST_MEDIA_VARIANTS,
  BACKEND_EVENTS.CREATE_ROLE,
  BACKEND_EVENTS.UPDATE_ROLE,
  BACKEND_EVENTS.DELETE_ROLE,
  BACKEND_EVENTS.ASSIGN_ROLE_TO_USER,
  BACKEND_EVENTS.REMOVE_ROLE_FROM_USER,
  BACKEND_EVENTS.INCREMENT_USER_TOKEN_VERSION,
  BACKEND_EVENTS.GET_ALL_ROLES,
  BACKEND_EVENTS.GET_ROLES_FOR_USER,
  BACKEND_EVENTS.LIST_ACTIVE_LOGIN_STRATEGIES,
  BACKEND_EVENTS.LIST_LOGIN_STRATEGIES,
  BACKEND_EVENTS.CREATE_PERMISSION,
  BACKEND_EVENTS.GET_ALL_PERMISSIONS,
  BACKEND_EVENTS.LIST_SETTINGS,
  BACKEND_EVENTS.GET_SETTING,
  BACKEND_EVENTS.GET_PUBLIC_SETTING,
  BACKEND_EVENTS.GET_PUBLIC_SETTINGS,
  BACKEND_EVENTS.GET_ALL_SETTINGS,
  BACKEND_EVENTS.GET_CMS_MODE,
  BACKEND_EVENTS.GET_USER_COUNT,
  BACKEND_EVENTS.LIST_MODULE_SETTINGS,
  BACKEND_EVENTS.LIST_MODULE_SETTINGS_SCHEMAS,
  BACKEND_EVENTS.LIST_NAVIGATION_LOCATIONS,
  BACKEND_EVENTS.LIST_NAVIGATION_MENUS,
  BACKEND_EVENTS.LIST_REGISTERED_SETTINGS_MODULES,
  BACKEND_EVENTS.LIST_SCHEDULED_CONTENT_ENTRIES,
  BACKEND_EVENTS.LIST_SEO_META,
  BACKEND_EVENTS.LIST_ACTIVE_STATIC_FRONTENDS,
  BACKEND_EVENTS.LIST_TRANSLATED_TEXTS,
  BACKEND_EVENTS.LIST_TRASHED_CONTENT_ENTRIES,
  BACKEND_EVENTS.GET_MODULE_REGISTRY,
  BACKEND_EVENTS.LIST_SYSTEM_MODULES,
  BACKEND_EVENTS.LIST_APPS,
  BACKEND_EVENTS.GET_APP,
  BACKEND_EVENTS.GET_APP_LAUNCH_INFO,
  BACKEND_EVENTS.LIST_BUILDER_APPS,
  BACKEND_EVENTS.LIST_IMPORTERS,
  BACKEND_EVENTS.LIST_EXPORTERS,
  BACKEND_EVENTS.GET_RECENT_NOTIFICATIONS,
  BACKEND_EVENTS.RESOLVE_SEO_META,
  BACKEND_EVENTS.GET_ALL_PAGES,
  BACKEND_EVENTS.GET_PAGES_BY_LANE,
  BACKEND_EVENTS.GET_PAGE_BY_ID,
  BACKEND_EVENTS.GET_PAGE_BY_SLUG,
  BACKEND_EVENTS.GET_START_PAGE,
  BACKEND_EVENTS.GET_CHILD_PAGES,
  BACKEND_EVENTS.SEARCH_PAGES,
  BACKEND_EVENTS.REMOVE_LISTENERS_BY_MODULE
]);

AGENT_ACCESS_EVENTS.forEach(eventName => HTTP_FORBIDDEN_EXTERNAL_EVENTS.add(eventName));
AGENT_MANAGER_EVENTS.forEach(eventName => HTTP_FORBIDDEN_EXTERNAL_EVENTS.add(eventName));
PLAINSPACE_PRESENTATION_EVENTS.forEach(eventName => HTTP_FORBIDDEN_EXTERNAL_EVENTS.add(eventName));
DESIGNER_MANAGER_EVENTS.forEach(eventName => HTTP_FORBIDDEN_EXTERNAL_EVENTS.add(eventName));

[
  BACKEND_EVENTS.ADD_FONT,
  BACKEND_EVENTS.ADD_LANGUAGE,
  BACKEND_EVENTS.ADD_SERVER_LOCATION,
  BACKEND_EVENTS.APP_LOADER_APP_EVENT,
  BACKEND_EVENTS.CREATE_LOCAL_FOLDER,
  BACKEND_EVENTS.CREATE_COMMENT,
  BACKEND_EVENTS.CREATE_SHARE_LINK,
  BACKEND_EVENTS.DELETE_LOCAL_ITEM,
  BACKEND_EVENTS.DELETE_COMMENT,
  BACKEND_EVENTS.DELETE_SERVER_LOCATION,
  BACKEND_EVENTS.FINALIZE_USER_LOGIN,
  BACKEND_EVENTS.GENERATE_ROBOTS_TXT,
  BACKEND_EVENTS.GENERATE_SEO_SITEMAP,
  BACKEND_EVENTS.GENERATE_XML_SITEMAP,
  BACKEND_EVENTS.GET_COMMENT,
  BACKEND_EVENTS.GET_SERVER_LOCATION,
  BACKEND_EVENTS.GET_SHARE_DETAILS,
  BACKEND_EVENTS.HTTP_REQUEST,
  BACKEND_EVENTS.ISSUE_REFRESH_TOKEN,
  BACKEND_EVENTS.LOGIN_WITH_STRATEGY,
  BACKEND_EVENTS.LIST_COMMENTS_FOR_ENTRY,
  BACKEND_EVENTS.LIST_FONT_PROVIDERS,
  BACKEND_EVENTS.LIST_FONTS,
  BACKEND_EVENTS.LIST_LOCAL_FOLDER,
  BACKEND_EVENTS.LIST_SERVER_LOCATIONS,
  BACKEND_EVENTS.MAKE_FILE_PUBLIC,
  BACKEND_EVENTS.PUBLISH_SCHEDULED_CONTENT_ENTRIES,
  BACKEND_EVENTS.PUBLIC_REGISTER,
  BACKEND_EVENTS.REGISTER_FONT_PROVIDER,
  BACKEND_EVENTS.REGISTER_NAVIGATION_LOCATION,
  BACKEND_EVENTS.RENAME_LOCAL_ITEM,
  BACKEND_EVENTS.REQUEST_DEPENDENCY,
  BACKEND_EVENTS.RESOLVE_CONTENT_PERMALINK,
  BACKEND_EVENTS.REVOKE_SHARE_LINK,
  BACKEND_EVENTS.SET_CMS_MODE,
  BACKEND_EVENTS.SET_FONT_PROVIDER_ENABLED,
  BACKEND_EVENTS.SET_LOGIN_STRATEGY_ENABLED,
  BACKEND_EVENTS.UPDATE_SERVER_LOCATION,
  BACKEND_EVENTS.UPLOAD_FILE_TO_FOLDER,
  BACKEND_EVENTS.USER_LOGIN,
  BACKEND_EVENTS.VALIDATE_TOKEN,
  BACKEND_EVENTS.UPDATE_COMMENT,
  BACKEND_EVENTS.UPDATE_COMMENT_STATUS,
  BACKEND_EVENTS.REGISTER_META_FIELD,
  BACKEND_EVENTS.GET_META_FIELD,
  BACKEND_EVENTS.LIST_META_FIELDS,
  BACKEND_EVENTS.DELETE_META_FIELD,
  BACKEND_EVENTS.SET_METADATA,
  BACKEND_EVENTS.GET_METADATA,
  BACKEND_EVENTS.GET_METADATA_VALUE,
  BACKEND_EVENTS.DELETE_METADATA,
  BACKEND_EVENTS.DELETE_METADATA_FOR_TARGET,
  BACKEND_EVENTS.UPSERT_REDIRECT_RULE,
  BACKEND_EVENTS.GET_REDIRECT_RULE,
  BACKEND_EVENTS.LIST_REDIRECT_RULES,
  BACKEND_EVENTS.DELETE_REDIRECT_RULE,
  BACKEND_EVENTS.RESOLVE_REDIRECT,
  BACKEND_EVENTS.RECORD_REDIRECT_HIT,
  BACKEND_EVENTS.LIST_REDIRECT_HITS,
  BACKEND_EVENTS.INDEX_SEARCH_DOCUMENT,
  BACKEND_EVENTS.GET_SEARCH_DOCUMENT,
  BACKEND_EVENTS.REMOVE_SEARCH_DOCUMENT,
  BACKEND_EVENTS.SEARCH_DOCUMENTS,
  BACKEND_EVENTS.REINDEX_CONTENT_ENTRIES
].forEach(eventName => HTTP_FORBIDDEN_EXTERNAL_EVENTS.add(eventName));

const COMMUNITY_QUERY_EVENT_PREFIX = /^(get|list|find|search|query|read|count|has|is|can|check|lookup|resolve)/i;

const COMMUNITY_FORBIDDEN_DIRECT_EVENTS = new Set([
  ...Array.from(HTTP_FORBIDDEN_EXTERNAL_EVENTS).filter(eventName =>
    eventName !== BACKEND_EVENTS.DB_SELECT && !COMMUNITY_QUERY_EVENT_PREFIX.test(eventName)
  ),
  BACKEND_EVENTS.CMS_ADMIN_API_REQUEST,
  BACKEND_EVENTS.CMS_PUBLIC_RUNTIME_REQUEST,
  BACKEND_EVENTS.DISPATCH_APP_EVENT,
  BACKEND_EVENTS.HTTP_REQUEST,
  BACKEND_EVENTS.REQUEST_DEPENDENCY,
  BACKEND_EVENTS.VALIDATE_TOKEN
]);

const SENSITIVE_SYSTEM_QUERY_EVENTS = new Set([
  BACKEND_EVENTS.GET_ALL_PERMISSIONS,
  BACKEND_EVENTS.GET_ALL_ROLES,
  BACKEND_EVENTS.GET_ALL_SETTINGS,
  BACKEND_EVENTS.GET_ALL_USERS,
  BACKEND_EVENTS.GET_APP,
  BACKEND_EVENTS.GET_APP_LAUNCH_INFO,
  BACKEND_EVENTS.GET_CMS_MODE,
  BACKEND_EVENTS.GET_MODULE_REGISTRY,
  BACKEND_EVENTS.CHECK_MODULE_UPDATES,
  BACKEND_EVENTS.LIST_PENDING_MODULE_ACCESS_REQUESTS,
  BACKEND_EVENTS.GET_MODULE_SETTING_VALUE,
  BACKEND_EVENTS.GET_MODULE_SETTINGS,
  BACKEND_EVENTS.GET_MODULE_SETTINGS_SCHEMA,
  BACKEND_EVENTS.GET_PUBLIC_SETTING,
  BACKEND_EVENTS.GET_PUBLIC_SETTINGS,
  BACKEND_EVENTS.GET_RECENT_NOTIFICATIONS,
  BACKEND_EVENTS.GET_ROLES_FOR_USER,
  BACKEND_EVENTS.GET_SETTING,
  BACKEND_EVENTS.GET_USER_COUNT,
  BACKEND_EVENTS.GET_USER_ACCESS,
  BACKEND_EVENTS.GET_USER_DETAILS_BY_ID,
  BACKEND_EVENTS.GET_USER_DETAILS_BY_USERNAME,
  BACKEND_EVENTS.LIST_ACTIVE_STATIC_FRONTENDS,
  BACKEND_EVENTS.LIST_ACTIVE_LOGIN_STRATEGIES,
  BACKEND_EVENTS.LIST_APPS,
  BACKEND_EVENTS.LIST_BUILDER_APPS,
  BACKEND_EVENTS.LIST_EXPORTERS,
  BACKEND_EVENTS.LIST_IMPORTERS,
  BACKEND_EVENTS.LIST_LOGIN_STRATEGIES,
  BACKEND_EVENTS.LIST_MODULE_SETTINGS,
  BACKEND_EVENTS.LIST_MODULE_SETTINGS_SCHEMAS,
  BACKEND_EVENTS.LIST_REGISTERED_SETTINGS_MODULES,
  BACKEND_EVENTS.LIST_SETTINGS,
  BACKEND_EVENTS.LIST_SYSTEM_MODULES,
  BACKEND_EVENTS.RESOLVE_MODULE_ACCESS_REQUEST,
  BACKEND_EVENTS.SITE_PRESETS_LIST
]);

const APP_FORBIDDEN_SENSITIVE_QUERY_EVENTS = SENSITIVE_SYSTEM_QUERY_EVENTS;

const APP_FORBIDDEN_DIRECT_EVENTS = new Set([
  ...Array.from(HTTP_FORBIDDEN_EXTERNAL_EVENTS).filter(eventName =>
    !AGENT_SURFACE_BRIDGE_EVENTS.has(eventName)
  ),
  ...APP_FORBIDDEN_SENSITIVE_QUERY_EVENTS,
  BACKEND_EVENTS.CMS_PUBLIC_RUNTIME_REQUEST,
  BACKEND_EVENTS.DISPATCH_APP_EVENT,
  BACKEND_EVENTS.VALIDATE_TOKEN
]);

function normalizeEventName(eventName) {
  return String(eventName || '').trim();
}

function stripHttpPayloadAuthMeta(payload = {}) {
  const source = payload && typeof payload === 'object' && !Array.isArray(payload) ? payload : {};
  const clean = { ...source };
  delete clean.jwt;
  delete clean.decodedJWT;
  return clean;
}

function isHttpPublicEvent(eventName) {
  return HTTP_PUBLIC_EVENTS.has(normalizeEventName(eventName));
}

function isHttpPublicTokenEvent(eventName) {
  return HTTP_PUBLIC_TOKEN_EVENTS.has(normalizeEventName(eventName));
}

function isHttpDirectContractEvent(eventName) {
  return HTTP_DIRECT_CONTRACT_EVENTS.has(normalizeEventName(eventName));
}

function hasRawPlaceholderPayload(payload = {}) {
  if (!payload || typeof payload !== 'object') return false;
  return (
    payload.table === '__rawSQL__' ||
    Boolean(payload?.data?.rawSQL) ||
    Boolean(payload?.where?.rawSQL)
  );
}

function explainExternalEventRejection(eventName, payload = {}) {
  const normalized = normalizeEventName(eventName);
  if (!normalized) return 'Missing eventName';

  if (hasRawPlaceholderPayload(payload)) {
    return 'Raw database placeholders cannot be called through /api/meltdown.';
  }

  if (HTTP_FORBIDDEN_EXTERNAL_EVENTS.has(normalized)) {
    return `Event "${normalized}" is internal and cannot be called through /api/meltdown. Use a public API or cmsAdminApiRequest.`;
  }

  if (!isHttpDirectContractEvent(normalized)) {
    return `Event "${normalized}" is not exposed through /api/meltdown. Use a public API, cmsAdminApiRequest, cmsPublicRuntimeRequest or dispatchAppEvent.`;
  }

  return null;
}

module.exports = {
  APP_FORBIDDEN_DIRECT_EVENTS,
  APP_FORBIDDEN_SENSITIVE_QUERY_EVENTS,
  COMMUNITY_FORBIDDEN_DIRECT_EVENTS,
  HTTP_DIRECT_CONTRACT_EVENTS,
  HTTP_FORBIDDEN_EXTERNAL_EVENTS,
  HTTP_PUBLIC_EVENTS,
  HTTP_PUBLIC_TOKEN_EVENTS,
  SENSITIVE_SYSTEM_QUERY_EVENTS,
  explainExternalEventRejection,
  hasRawPlaceholderPayload,
  isHttpDirectContractEvent,
  isHttpPublicEvent,
  isHttpPublicTokenEvent,
  stripHttpPayloadAuthMeta
};
