/**
 * mother/modules/databaseManager/placeholders/builtinPlaceholders.js
 *
 * The single list of all built-in placeholder strings, shared by Postgres and Mongo.
 */
module.exports = [
  // UserManagement
  'INIT_USER_MANAGEMENT',
  'INIT_B2B_FIELDS',
  'ADD_USER_FIELD',

  // settingsManager
  'INIT_SETTINGS_SCHEMA',
  'INIT_SETTINGS_TABLES',
  'CHECK_AND_ALTER_SETTINGS_TABLES',
  'GET_SETTING',
  'UPSERT_SETTING',
  'LIST_SETTINGS',
  'DELETE_SETTING',
  'GET_ALL_SETTINGS',

  // pagesManager
  'INIT_PAGES_SCHEMA',
  'INIT_PAGES_TABLE',
  'CHECK_AND_ALTER_PAGES_TABLE',
  'CREATE_PAGE',
  'ADD_PARENT_CHILD_RELATION',
  'GET_ALL_PAGES',
  'GET_CHILD_PAGES',
  'GET_PAGE_BY_ID',
  'GET_PAGE_BY_SLUG',
  'GET_PAGES_BY_LANE',
  'UPDATE_PAGE',
  'DELETE_PAGE',
  'GET_START_PAGE',
  'SET_AS_START',
  'GENERATE_XML_SITEMAP',
  'SEARCH_PAGES',

  // ContentEngine
  'INIT_CONTENT_ENGINE_SCHEMA',
  'INIT_CONTENT_ENGINE_TABLES',
  'UPSERT_CONTENT_TYPE',
  'GET_CONTENT_TYPE',
  'LIST_CONTENT_TYPES',
  'CREATE_CONTENT_ENTRY',
  'UPDATE_CONTENT_ENTRY',
  'GET_CONTENT_ENTRY',
  'GET_CONTENT_ENTRY_BY_SOURCE',
  'FIND_CONTENT_ENTRY_CONFLICT',
  'RESOLVE_CONTENT_PERMALINK',
  'LIST_CONTENT_ENTRIES',
  'LIST_TRASHED_CONTENT_ENTRIES',
  'LIST_SCHEDULED_CONTENT_ENTRIES',
  'LIST_CONTENT_REVISIONS',
  'GET_CONTENT_REVISION',
  'RESTORE_CONTENT_REVISION',
  'TRASH_CONTENT_ENTRY',
  'RESTORE_CONTENT_ENTRY',
  'UPSERT_CONTENT_TAXONOMY',
  'GET_CONTENT_TAXONOMY',
  'LIST_CONTENT_TAXONOMIES',
  'DELETE_CONTENT_TAXONOMY',
  'UPSERT_CONTENT_TERM',
  'GET_CONTENT_TERM',
  'LIST_CONTENT_TERMS',
  'DELETE_CONTENT_TERM',
  'ASSIGN_CONTENT_TERM',
  'UNASSIGN_CONTENT_TERM',
  'LIST_CONTENT_TERMS_FOR_ENTRY',

  // CommentsManager
  'INIT_COMMENTS_SCHEMA',
  'INIT_COMMENTS_TABLES',
  'CREATE_COMMENT',
  'GET_COMMENT',
  'LIST_COMMENTS_FOR_ENTRY',
  'UPDATE_COMMENT',
  'UPDATE_COMMENT_STATUS',
  'DELETE_COMMENT',

  // NavigationManager
  'INIT_NAVIGATION_SCHEMA',
  'INIT_NAVIGATION_TABLES',
  'UPSERT_NAVIGATION_LOCATION',
  'LIST_NAVIGATION_LOCATIONS',
  'UPSERT_NAVIGATION_MENU',
  'GET_NAVIGATION_MENU',
  'LIST_NAVIGATION_MENUS',
  'ADD_NAVIGATION_MENU_ITEM',
  'SET_NAVIGATION_MENU_ITEMS',
  'GET_NAVIGATION_MENU_ITEM',
  'LIST_NAVIGATION_MENU_ITEMS',
  'UPDATE_NAVIGATION_MENU_ITEM',
  'DELETE_NAVIGATION_MENU_ITEM',

  // SeoManager
  'INIT_SEO_SCHEMA',
  'INIT_SEO_TABLES',
  'UPSERT_SEO_META',
  'GET_SEO_META',
  'LIST_SEO_META',
  'DELETE_SEO_META',

  // SearchManager
  'INIT_SEARCH_SCHEMA',
  'INIT_SEARCH_TABLES',
  'UPSERT_SEARCH_DOCUMENT',
  'GET_SEARCH_DOCUMENT',
  'SEARCH_DOCUMENTS',
  'DELETE_SEARCH_DOCUMENT',

  // RedirectManager
  'INIT_REDIRECT_SCHEMA',
  'INIT_REDIRECT_TABLES',
  'UPSERT_REDIRECT_RULE',
  'GET_REDIRECT_RULE',
  'LIST_REDIRECT_RULES',
  'DELETE_REDIRECT_RULE',
  'RESOLVE_REDIRECT',
  'RECORD_REDIRECT_HIT',
  'LIST_REDIRECT_HITS',

  // MetadataManager
  'INIT_METADATA_SCHEMA',
  'INIT_METADATA_TABLES',
  'UPSERT_META_FIELD',
  'GET_META_FIELD',
  'LIST_META_FIELDS',
  'DELETE_META_FIELD',
  'UPSERT_METADATA_VALUE',
  'GET_METADATA_VALUES',
  'DELETE_METADATA_VALUE',
  'DELETE_METADATA_FOR_TARGET',

  // WorkflowManager
  'INIT_WORKFLOW_SCHEMA',
  'INIT_WORKFLOW_TABLES',
  'ACQUIRE_CONTENT_LOCK',
  'REFRESH_CONTENT_LOCK',
  'RELEASE_CONTENT_LOCK',
  'GET_CONTENT_LOCK',
  'UPSERT_CONTENT_AUTOSAVE',
  'GET_CONTENT_AUTOSAVE',
  'LIST_CONTENT_AUTOSAVES',
  'DELETE_CONTENT_AUTOSAVE',
  'UPSERT_CONTENT_REVIEW',
  'UPDATE_CONTENT_REVIEW_STATUS',
  'GET_CONTENT_REVIEW',
  'LIST_CONTENT_REVIEWS',

  // ModuleLoader
  'DROP_MODULE_DATABASE',
  'INIT_MODULE_REGISTRY_TABLE',
  'CHECK_MODULE_REGISTRY_COLUMNS',
  'ALTER_MODULE_REGISTRY_COLUMNS',
  'SELECT_MODULE_REGISTRY',
  'SELECT_MODULE_BY_NAME',
  'LIST_ACTIVE_GRAPES_MODULES',

  // AppLoader
  'INIT_APP_REGISTRY_TABLE',
  'INSERT_APP_REGISTRY_ENTRY',
  'UPDATE_APP_REGISTRY_ENTRY',
  'SELECT_APP_BY_NAME',
  'LIST_APP_REGISTRY',

  // DependencyLoader
  'CHECK_DB_EXISTS_DEPENDENCYLOADER',
  'INIT_DEPENDENCYLOADER_SCHEMA',
  'INIT_DEPENDENCYLOADER_TABLE',
  'LIST_DEPENDENCYLOADER_DEPENDENCIES',

  // UnifiedSettings
  'LIST_MODULE_SETTINGS',

  // ServerManager
  'INIT_SERVERMANAGER_SCHEMA',
  'SERVERMANAGER_ADD_LOCATION',
  'SERVERMANAGER_GET_LOCATION',
  'SERVERMANAGER_LIST_LOCATIONS',
  'SERVERMANAGER_DELETE_LOCATION',
  'SERVERMANAGER_UPDATE_LOCATION',

  // MediaManager
  'INIT_MEDIA_SCHEMA',
  'MEDIA_ADD_FILE',
  'MEDIA_LIST_FILES',
  'MEDIA_DELETE_FILE',
  'MEDIA_UPDATE_FILE',
  'UPSERT_MEDIA_ATTACHMENT',
  'GET_MEDIA_ATTACHMENT',
  'LIST_MEDIA_ATTACHMENTS',
  'DELETE_MEDIA_ATTACHMENT',
  'UPSERT_MEDIA_VARIANT',
  'LIST_MEDIA_VARIANTS',
  'DELETE_MEDIA_VARIANT',
  'LINK_MEDIA_ATTACHMENT',
  'UNLINK_MEDIA_ATTACHMENT',
  'LIST_MEDIA_FOR_CONTENT',
  'LIST_CONTENT_FOR_MEDIA',

  // ShareManager
  'INIT_SHARED_LINKS_TABLE',
  'CREATE_SHARE_LINK',
  'REVOKE_SHARE_LINK',
  'GET_SHARE_LINK',

  // TranslationManager
  'INIT_TRANSLATION_TABLES',
  'UPSERT_TRANSLATED_TEXT',
  'UPDATE_TRANSLATED_TEXT',
  'GET_TRANSLATED_TEXT',
  'LIST_TRANSLATED_TEXTS',
  'DELETE_TRANSLATED_TEXT',
  'UPSERT_TRANSLATION_LANGUAGE',
  'GET_TRANSLATION_LANGUAGE',
  'LIST_TRANSLATION_LANGUAGES',
  'DELETE_TRANSLATION_LANGUAGE',

  // WidgetManager
  /* public lane */
  'INIT_WIDGETS_TABLE_PUBLIC',
  'UPDATE_WIDGET_PUBLIC',
  'DELETE_WIDGET_PUBLIC',

  /*  admin lane */
  'INIT_WIDGETS_TABLE_ADMIN',
  'UPDATE_WIDGET_ADMIN',
  'DELETE_WIDGET_ADMIN',

  //plainSpace
  'INIT_PLAINSPACE_LAYOUTS',
  'INIT_PLAINSPACE_LAYOUT_TEMPLATES',
  'INIT_PLAINSPACE_PUBLISHED_DESIGNS',
  'UPSERT_PLAINSPACE_LAYOUT_TEMPLATE',
  'GET_PLAINSPACE_LAYOUT_TEMPLATE',
  'GET_PLAINSPACE_LAYOUT_TEMPLATE_NAMES',
  'UPSERT_PLAINSPACE_PUBLISHED_DESIGN',
  'GET_PLAINSPACE_PUBLISHED_DESIGN',
  'UPSERT_PLAINSPACE_LAYOUT',
  'GET_PLAINSPACE_LAYOUT',
  'GET_ALL_PLAINSPACE_LAYOUTS',
  'INIT_PLAINSPACE_WIDGET_INSTANCES',
  'UPSERT_WIDGET_INSTANCE',
  'GET_WIDGET_INSTANCE',
  'SET_GLOBAL_LAYOUT_TEMPLATE',
  'DELETE_LAYOUT_TEMPLATE',
  'GET_GLOBAL_LAYOUT_TEMPLATE'

];
